Algoritmo "Questão4 - Tabuada de um número"
//4. Faça um fluxograma e pseudocódigo que receba um número e mostre a
//tabuada da multiplicação para esse número.

Var
   numero, multiplicador, resultado: Inteiro

Inicio
   Escreva("Digite um número para calcular a tabuada de multiplicação: ")
   Leia(numero)

   Para multiplicador de 1 ate 10 faca
      resultado <- numero * multiplicador
      Escreval(numero, " x ", multiplicador, " = ", resultado)
   FimPara
FimAlgoritmo

